### ISSUE TITLE
Define in module produce error

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [bevyengine/naga_oil#45]
Inside a GLSL module I'm doing 
```glsl
#ifndef FNC_RATIO
#define FNC_RATIO
vec2 ratio(in vec2 st, in vec2 s) {
    return mix( vec2((st.x*s.x/s.y)-(s.x*.5-s.y*.5)/s.y,st.y),
                vec2(st.x,st.y*(s.y/s.x)-(s.y*.5-s.x*.5)/s.x),
                step(s.x,s.y));
}
#endif
```

Produce the following error

```
ComposerError { 
    inner: DefineInModule(100), 
    source: Constructing { 
        path: "_module.glsl", 
        source: "..."
    }
}
```

The line that produce the error in question is 
```
...
#define FNC_RATIO
...
```

Is there a way of using the following pattern without errors?

```glsl
#ifndef SOME_DEFINE
#define SOME_DEFINE
...
#endif
```

**Comment by robtfm** [comment]
generally no, there's way of doing that. but it is not necessary either: if you include the same module multiple times you still only get one copy of it in the final output, so this kind of construct isn't necessary.

naga_oil generally works more like rust than like a c-preprocessor. `#define`s are like rust's `#[cfg(..)]`. you *can* specify them directly in shaders but only in the entry-point / top level, otherwise things get very confusing - internally modules are compiled once per `ShaderDef` set, so allowing modules to also define new `ShaderDefs` is not really tractable. normally they are specified externally and passed to `Composer::make_naga_module`.

also fyi - using `error.emit_to_string(&composer)` will give you more readable errors.
