### ISSUE TITLE
Invalid escape character

### ISSUE THREAD

**Issue by GuiAmPm** [bevyengine/naga_oil#50]
Running Bevy 0.11.2 on an ArchLinux x64 is throwing an error when trying to build the following regex:

```rust
static RE_COMMENT: once_cell::sync::Lazy<Regex> =
    once_cell::sync::Lazy::new(|| Regex::new(r"(\/\/|\/\*|\*\/)").unwrap());
```

Shouldn't it be `r"(//|/\*|\*/)"` ?

**Comment by mockersf** [comment]
Could you try deleting your lockfile and updating?

**Comment by robtfm** [comment]
seems like allowing no-op escapes was added in [regex 1.8.0](https://github.com/rust-lang/regex/issues/501), so `cargo update` or deleting cargo.lock should work.

we should also change the regex or bump the required version though. i think changing the regex is better.

i'm not sure it's worth making another 0.8.x release, since the fix is quite straight forward, but we could do that too if there's a need.

**Comment by GuiAmPm** [comment]
@robtfm @mockersf 
Removing the lock file does work. Haven't really try `cargo update`, but would probably have the same effect.
At same time I've made the PR to change the Regex.

Thanks for the help!
